### ISSUE TITLE
[bug] Non existing files in .list files

### ISSUE THREAD

**Issue by Nic30** [steveicarus/ivtest#10]
Hello, there are some filenames in in tests, which seems to be incorrect.
Does the test runner reports these errors?

```  
      # name present in .list file: real name present in FS
      {
            "br_ml201801012a": "br_ml20181012a",
            "br_ml201801012b": "br_ml20181012b",
            "br_ml201801012c": "br_ml20181012c",
            "br_ml201801012d": "br_ml20181012d",
            "struct_packe_write_read": "struct_packed_write_read",
            "struct_packe_write_read2": "struct_packed_write_read2",
            "sv_string_index": "string_index",
            "sv_timeunit_prec": "sv_timeunit_prec1",
            "sv_timeunit_prec_fail": "sv_timeunit_prec_fail1",
        }
```

**Comment by martinwhitaker** [comment]
The test scripts did not catch a missing file in the case that a test was expected to fail at the compile stage but didn't have a gold file for comparing the compiler output. I've modified the scripts to check that the source file exists before running the compiler, and fixed the typo in the br_ml20181012 tests.

The other differences you have found are in regress-v0.8.list. That has been unmaintained for many years. Arguably we should delete it now.

**Comment by Nic30** [comment]
> The other differences you have found are in regress-v0.8.list. That has been unmaintained for many years. Arguably we should delete it now.

still present
